<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_yr9d8DmHEeyYv-1DyfdLZw" name="Project_Validation_Diagram_JANAKIEWICZ_ADRIAN" version="1.8" author="adrian" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_yr-sQTmHEeyYv-1DyfdLZw" name="Create proposal" version="1.3">
      <elements xmi:type="process:Lane" xmi:id="_yr-sQjmHEeyYv-1DyfdLZw" name="Improvement Manager" actor="_yr-s1DmHEeyYv-1DyfdLZw">
        <elements xmi:type="process:Task" xmi:id="_yr-sQzmHEeyYv-1DyfdLZw" name="Validate" outgoing="_yr-sxjmHEeyYv-1DyfdLZw" incoming="_yr-swzmHEeyYv-1DyfdLZw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yr-sRDmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yr-sRTmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yr-sRjmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_yr-sRzmHEeyYv-1DyfdLZw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yr-sSDmHEeyYv-1DyfdLZw" name="proposalPoolVar" content="proposalPoolVar" type="TYPE_VARIABLE" returnType="com.company.model.ProjectProposal">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yr-sSTmHEeyYv-1DyfdLZw" name="proposalPoolVar" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.ProjectProposal"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yr-sSjmHEeyYv-1DyfdLZw" name="additionalInformation" content="additionalInformation" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yr-sSzmHEeyYv-1DyfdLZw" name="additionalInformation">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_yr-sTDmHEeyYv-1DyfdLZw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yr-sTTmHEeyYv-1DyfdLZw" type="JAVA_METHOD" expression="setAdditionalInformations">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yr-sTjmHEeyYv-1DyfdLZw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yr-sTzmHEeyYv-1DyfdLZw" name="proposalApproved" content="proposalApproved" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_yr-sUDmHEeyYv-1DyfdLZw" name="proposalApproved" dataType="_yr-s6DmHEeyYv-1DyfdLZw"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yr-sUTmHEeyYv-1DyfdLZw" name="approved" content="approved" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yr-sUjmHEeyYv-1DyfdLZw" name="approved" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_yr-sUzmHEeyYv-1DyfdLZw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yr-sVDmHEeyYv-1DyfdLZw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yr-sVTmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yr-sVjmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yr-sVzmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yr-sWDmHEeyYv-1DyfdLZw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yr-sWTmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_yr-sWjmHEeyYv-1DyfdLZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_yr-sWzmHEeyYv-1DyfdLZw" name="ValidateProposal" content="989b498a-a17c-4293-b249-6f07f79a1b29" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_yr-sXDmHEeyYv-1DyfdLZw">
            <inputs xmi:type="process:ContractInput" xmi:id="_yr-sXTmHEeyYv-1DyfdLZw" name="approved" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_yr-sXjmHEeyYv-1DyfdLZw"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_yr-sXzmHEeyYv-1DyfdLZw" name="additionalInformation">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_yr-sYDmHEeyYv-1DyfdLZw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_yr-sYTmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_yr-sYjmHEeyYv-1DyfdLZw" name="Approved?" outgoing="_yr-syTmHEeyYv-1DyfdLZw _yr-szTmHEeyYv-1DyfdLZw" incoming="_yr-sxjmHEeyYv-1DyfdLZw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yr-sYzmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yr-sZDmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yr-sZTmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_yr-sZjmHEeyYv-1DyfdLZw" name="Send proposal" incoming="_yr-syTmHEeyYv-1DyfdLZw" outgoingMessages="_9uZbMDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yr-sZzmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yr-saDmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yr-saTmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_yr-sajmHEeyYv-1DyfdLZw" name="ProposalSent">
            <correlation xmi:type="process:Correlation" xmi:id="_yr-sazmHEeyYv-1DyfdLZw">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_yr-sbDmHEeyYv-1DyfdLZw"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_dWSoQUDXEeybB7ET8tJHKg" name="Project Validation" content="Project Validation"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_dWSoQEDXEeybB7ET8tJHKg" name="Proposal made" content="Proposal made"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_yr-sbzmHEeyYv-1DyfdLZw">
              <expressions xmi:type="expression:ListExpression" xmi:id="_yr-scDmHEeyYv-1DyfdLZw">
                <expressions xmi:type="expression:Expression" xmi:id="_yr-scTmHEeyYv-1DyfdLZw" name="title" content="title" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_yr-scjmHEeyYv-1DyfdLZw" name="proposal.title" content="proposalPoolVar.title" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yr-sczmHEeyYv-1DyfdLZw" name="proposalPoolVar" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.ProjectProposal"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_yr-sdDmHEeyYv-1DyfdLZw">
                <expressions xmi:type="expression:Expression" xmi:id="_yr-sdTmHEeyYv-1DyfdLZw" name="description" content="description" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_yr-sdjmHEeyYv-1DyfdLZw" name="proposal.description" content="proposalPoolVar.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yr-sdzmHEeyYv-1DyfdLZw" name="proposalPoolVar" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.ProjectProposal"/>
                </expressions>
              </expressions>
              <expressions xmi:type="expression:ListExpression" xmi:id="_yr-sezmHEeyYv-1DyfdLZw">
                <expressions xmi:type="expression:Expression" xmi:id="_yr-sfDmHEeyYv-1DyfdLZw" name="applicantEmail" content="applicantEmail" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_yr-sfTmHEeyYv-1DyfdLZw" name="emailOfApplicant" content="return apiAccessor.getIdentityAPI()&#xA;&#x9;&#x9;.getUserWithProfessionalDetails(&#xA;&#x9;&#x9;&#x9;apiAccessor.getProcessAPI()&#xA;&#x9;&#x9;&#x9;&#x9;.getProcessInstance(processInstanceId)&#xA;&#x9;&#x9;&#x9;&#x9;.getStartedBy()&#xA;&#x9;&#x9;)&#xA;&#x9;&#x9;.getContactData()&#xA;&#x9;&#x9;.getEmail()&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_XLlnQEDcEeybB7ET8tJHKg" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_XLlnQUDcEeybB7ET8tJHKg" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                </expressions>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_yr-sgDmHEeyYv-1DyfdLZw" name="Notify proposal rejection" outgoing="_yr-s0DmHEeyYv-1DyfdLZw" incoming="_yr-szTmHEeyYv-1DyfdLZw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yr-sgTmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yr-sgjmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yr-sgzmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_yr-shDmHEeyYv-1DyfdLZw" name="notifyProposalRefusal" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_yr-shTmHEeyYv-1DyfdLZw" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-shjmHEeyYv-1DyfdLZw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_yr-shzmHEeyYv-1DyfdLZw" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-siDmHEeyYv-1DyfdLZw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_yr-siTmHEeyYv-1DyfdLZw" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-sijmHEeyYv-1DyfdLZw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_yr-sizmHEeyYv-1DyfdLZw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-sjDmHEeyYv-1DyfdLZw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_yr-sjTmHEeyYv-1DyfdLZw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-sjjmHEeyYv-1DyfdLZw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_yr-sjzmHEeyYv-1DyfdLZw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-skDmHEeyYv-1DyfdLZw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_yr-skTmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-skjmHEeyYv-1DyfdLZw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_yr-skzmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-slDmHEeyYv-1DyfdLZw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_yr-slTmHEeyYv-1DyfdLZw" name="from()" content="&quot;project_status@acme.com&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-sljmHEeyYv-1DyfdLZw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_yr-slzmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-smDmHEeyYv-1DyfdLZw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_yr-smTmHEeyYv-1DyfdLZw" name="to()" content="return apiAccessor.getIdentityAPI()&#xA;&#x9;&#x9;.getUserWithProfessionalDetails(&#xA;&#x9;&#x9;&#x9;apiAccessor.getProcessAPI()&#xA;&#x9;&#x9;&#x9;&#x9;.getProcessInstance(processInstanceId)&#xA;&#x9;&#x9;&#x9;&#x9;.getStartedBy()&#xA;&#x9;&#x9;)&#xA;&#x9;&#x9;.getContactData()&#xA;&#x9;&#x9;.getEmail()&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_Y_mikEDcEeybB7ET8tJHKg" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_Y_mikUDcEeybB7ET8tJHKg" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-smjmHEeyYv-1DyfdLZw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_yr-smzmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-snDmHEeyYv-1DyfdLZw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_yr-snTmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-snjmHEeyYv-1DyfdLZw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_yr-snzmHEeyYv-1DyfdLZw" name="Proposal rejected" content="Proposal rejected" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-soDmHEeyYv-1DyfdLZw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_yr-soTmHEeyYv-1DyfdLZw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-sojmHEeyYv-1DyfdLZw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_yr-sozmHEeyYv-1DyfdLZw" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-spDmHEeyYv-1DyfdLZw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_yr-spTmHEeyYv-1DyfdLZw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-spjmHEeyYv-1DyfdLZw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_yr-spzmHEeyYv-1DyfdLZw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-sqDmHEeyYv-1DyfdLZw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_yr-sqTmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yr-sqjmHEeyYv-1DyfdLZw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_yr-sqzmHEeyYv-1DyfdLZw"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yr-srDmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yr-srTmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yr-srjmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yr-srzmHEeyYv-1DyfdLZw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yr-ssDmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_yr-ssTmHEeyYv-1DyfdLZw" name="Proposal rejected" incoming="_yr-s0DmHEeyYv-1DyfdLZw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yr-ssjmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yr-sszmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yr-stDmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_yr-stTmHEeyYv-1DyfdLZw" name="Employee" actor="_yr-s0zmHEeyYv-1DyfdLZw">
        <elements xmi:type="process:StartEvent" xmi:id="_yr-stjmHEeyYv-1DyfdLZw" name="Prepare proposal draft" outgoing="_yr-swzmHEeyYv-1DyfdLZw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yr-stzmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yr-suDmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yr-suTmHEeyYv-1DyfdLZw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_yr-sujmHEeyYv-1DyfdLZw" name="proposalPoolVar" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.ProjectProposal">
        <defaultValue xmi:type="expression:Expression" xmi:id="_yr-suzmHEeyYv-1DyfdLZw" name="initProposal()" content="def projectProposalVar = new com.company.model.ProjectProposal()&#xA;projectProposalVar.description = proposalInput?.description&#xA;projectProposalVar.title = proposalInput?.title&#xA;return projectProposalVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.ProjectProposal">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_yr-svDmHEeyYv-1DyfdLZw" name="proposalInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_yr-svTmHEeyYv-1DyfdLZw" name="proposalApproved" dataType="_yr-s6DmHEeyYv-1DyfdLZw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_yr-svjmHEeyYv-1DyfdLZw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_yr-svzmHEeyYv-1DyfdLZw">
        <targetForm xmi:type="expression:Expression" xmi:id="_yr-swDmHEeyYv-1DyfdLZw" name="proposalInit" content="02fd8803-e341-4fed-bc84-31ebd16f9241" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_yr-swTmHEeyYv-1DyfdLZw">
        <targetForm xmi:type="expression:Expression" xmi:id="_-RDU8EDeEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yr-swzmHEeyYv-1DyfdLZw" target="_yr-sQzmHEeyYv-1DyfdLZw" source="_yr-stjmHEeyYv-1DyfdLZw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yr-sxDmHEeyYv-1DyfdLZw"/>
        <condition xmi:type="expression:Expression" xmi:id="_yr-sxTmHEeyYv-1DyfdLZw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yr-sxjmHEeyYv-1DyfdLZw" target="_yr-sYjmHEeyYv-1DyfdLZw" source="_yr-sQzmHEeyYv-1DyfdLZw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yr-sxzmHEeyYv-1DyfdLZw"/>
        <condition xmi:type="expression:Expression" xmi:id="_yr-syDmHEeyYv-1DyfdLZw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yr-syTmHEeyYv-1DyfdLZw" name="Yes" target="_yr-sZjmHEeyYv-1DyfdLZw" source="_yr-sYjmHEeyYv-1DyfdLZw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yr-syjmHEeyYv-1DyfdLZw"/>
        <condition xmi:type="expression:Expression" xmi:id="_yr-syzmHEeyYv-1DyfdLZw" name="proposalApproved" content="proposalApproved == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_yr-szDmHEeyYv-1DyfdLZw" name="proposalApproved" dataType="_yr-s6DmHEeyYv-1DyfdLZw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yr-szTmHEeyYv-1DyfdLZw" name="No" target="_yr-sgDmHEeyYv-1DyfdLZw" source="_yr-sYjmHEeyYv-1DyfdLZw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yr-szjmHEeyYv-1DyfdLZw"/>
        <condition xmi:type="expression:Expression" xmi:id="_yr-szzmHEeyYv-1DyfdLZw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yr-s0DmHEeyYv-1DyfdLZw" target="_yr-ssTmHEeyYv-1DyfdLZw" source="_yr-sgDmHEeyYv-1DyfdLZw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yr-s0TmHEeyYv-1DyfdLZw"/>
        <condition xmi:type="expression:Expression" xmi:id="_yr-s0jmHEeyYv-1DyfdLZw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_yr-s0zmHEeyYv-1DyfdLZw" name="Employee" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_yr-s1DmHEeyYv-1DyfdLZw" name="Improvement Manager"/>
      <contract xmi:type="process:Contract" xmi:id="_yr-s1TmHEeyYv-1DyfdLZw">
        <inputs xmi:type="process:ContractInput" xmi:id="_yr-s1jmHEeyYv-1DyfdLZw" name="proposalInput" type="COMPLEX" dataReference="proposalPoolVar">
          <inputs xmi:type="process:ContractInput" xmi:id="_yr-s1zmHEeyYv-1DyfdLZw" name="description"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_yr-s2DmHEeyYv-1DyfdLZw" name="title"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yr-s2TmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_yr-s2jmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_yr-s2zmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yr-s3DmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_yr-s3TmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_yr-s3jmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yr-s3zmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_yr-s4DmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_yr-s4TmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yr-s4jmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_yr-s4zmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_yr-s5DmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yr-s5TmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_yr-s5jmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_yr-s5zmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_2R1YcDmHEeyYv-1DyfdLZw" name="Project Validation" version="1.8">
      <elements xmi:type="process:Lane" xmi:id="_3F7u4DmHEeyYv-1DyfdLZw" name="R&amp;D" actor="_DDK88DmIEeyYv-1DyfdLZw">
        <elements xmi:type="process:Task" xmi:id="_sCqZQDmIEeyUrPCKx7tUYQ" name="Analyze impact" outgoing="_pL2kMDmIEeyUrPCKx7tUYQ" incoming="_oZPbgDmIEeyUrPCKx7tUYQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oZKjAjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oZKjATmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oZLKEDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oZLKETmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oZLKEjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oZLKEzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oZLKFTmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oZLKFDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_sCrAWTmIEeyUrPCKx7tUYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_oJDtoEDfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_sCrAWDmIEeyUrPCKx7tUYQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_sCrAWzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_gn4cMEDUEeyXTtv0MKkOFw" name="Do project" outgoing="_23PWIDmIEeyUrPCKx7tUYQ" incoming="_2PVooDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gn5DQUDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gn5DQEDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gn5DQkDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gn5DRUDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gn5DRkDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gn5DR0DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gn5DSUDUEeyXTtv0MKkOFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gn5DSEDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_goKwEEDUEeyXTtv0MKkOFw" subprocessTarget="project_persistenceId">
            <processSource xmi:type="expression:Expression" xmi:id="_goKwEUDUEeyXTtv0MKkOFw" name="project_persistenceId()" content="project.persistenceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_goKwEkDUEeyXTtv0MKkOFw" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
            </processSource>
          </inputMappings>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_gn6RYUDUEeyXTtv0MKkOFw" name="Do project" content="Do project" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_gn5DREDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_3XRWgDmHEeyYv-1DyfdLZw" name="Management" actor="_AXKCoDmIEeyYv-1DyfdLZw">
        <elements xmi:type="process:Task" xmi:id="_f8i8ADmIEeyUrPCKx7tUYQ" name="Approve proposal" outgoing="_XnlcMDmIEeyUrPCKx7tUYQ" incoming="_g-GqMDmJEeyUrPCKx7tUYQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WS1PwDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WS0osDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WS1PwTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_0SnB8DmjEeyqY_BK0Fb6wA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_0SnB8TmjEeyqY_BK0Fb6wA" name="project" content="project" type="TYPE_VARIABLE" returnType="com.company.model.Project">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0ymJkDmjEeyqY_BK0Fb6wA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_0SnB8jmjEeyqY_BK0Fb6wA" name="proposalOK" content="proposalOK" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2JUr8DmjEeyqY_BK0Fb6wA" name="proposalOK" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_2JUr8TmjEeyqY_BK0Fb6wA"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_0SnB8zmjEeyqY_BK0Fb6wA" type="JAVA_METHOD" expression="setProposalOK">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WS1PwjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WS120DmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WS120TmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WS2d4DmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WS120jmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_gWIgsDmIEeyUrPCKx7tUYQ" name="5 days" outgoing="_jh7HQDmIEeyUrPCKx7tUYQ">
            <condition xmi:type="expression:Expression" xmi:id="_bX2MUDmJEeyUrPCKx7tUYQ" name="5 Days 00:00:00" content="432000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_f8lYQzmIEeyUrPCKx7tUYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_QaBy4TmUEeyqY_BK0Fb6wA" name="ApproveProposal" content="b0f936b7-39e3-4077-a124-6d85894c4a3c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_f8lYQjmIEeyUrPCKx7tUYQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_xRjrwDmjEeyqY_BK0Fb6wA" name="proposalOK" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_xRjrwTmjEeyqY_BK0Fb6wA"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_f8l_UDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_szmuADmIEeyUrPCKx7tUYQ" name="Validate Project" outgoing="_0DomEDmIEeyUrPCKx7tUYQ" incoming="_pL2kMDmIEeyUrPCKx7tUYQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pLxrsTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pLxrsDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pLxrsjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_RZf4kDmkEeyqY_BK0Fb6wA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RZf4kTmkEeyqY_BK0Fb6wA" name="project" content="project" type="TYPE_VARIABLE" returnType="com.company.model.Project">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RusFcDmkEeyqY_BK0Fb6wA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RZf4kjmkEeyqY_BK0Fb6wA" name="projectOK" content="projectOK" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_S1CpgDmkEeyqY_BK0Fb6wA" name="projectOK" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_S1CpgTmkEeyqY_BK0Fb6wA"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RZf4kzmkEeyqY_BK0Fb6wA" type="JAVA_METHOD" expression="setProjectOK">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pLxrszmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pLxrtDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pLxrtTmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pLxrtzmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pLxrtjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_vWpSgDmIEeyUrPCKx7tUYQ" name="4 days" outgoing="_xS8AEDmIEeyUrPCKx7tUYQ">
            <condition xmi:type="expression:Expression" xmi:id="_dLD2YDmJEeyUrPCKx7tUYQ" name="4 Days 00:00:00" content="345600000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_szn8KTmIEeyUrPCKx7tUYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_oJDtoUDfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_szn8KDmIEeyUrPCKx7tUYQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_CF7A0DmkEeyqY_BK0Fb6wA" name="projectOK" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_CF7A0TmkEeyqY_BK0Fb6wA"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_szn8KzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_3pCb8DmHEeyYv-1DyfdLZw" name="Management Assistant" actor="_-I6pcDmHEeyYv-1DyfdLZw">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_SbvpcDmIEeyUrPCKx7tUYQ" name="Proposal made" outgoing="_g-GqMDmJEeyUrPCKx7tUYQ" event="ProposalSent" incomingMessag="_9uZbMDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SbxeoTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SbxeoDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SbxeojmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_LUxxUDmJEeyUrPCKx7tUYQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_LUxxUTmJEeyUrPCKx7tUYQ" name="project" content="project" type="TYPE_VARIABLE" returnType="com.company.model.Project">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_S-QrMDmJEeyUrPCKx7tUYQ" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_LUxxUjmJEeyUrPCKx7tUYQ" name="title" content="title" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_LUxxUzmJEeyUrPCKx7tUYQ" type="JAVA_METHOD" expression="setTitle">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_LU00oDmJEeyUrPCKx7tUYQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_LU00oTmJEeyUrPCKx7tUYQ" name="project" content="project" type="TYPE_VARIABLE" returnType="com.company.model.Project">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TQC-wDmJEeyUrPCKx7tUYQ" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_LU00ojmJEeyUrPCKx7tUYQ" name="description" content="description" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_LU00ozmJEeyUrPCKx7tUYQ" type="JAVA_METHOD" expression="setProposal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
          <messageContent xmi:type="expression:Operation" xmi:id="_LU2p0DmJEeyUrPCKx7tUYQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_LU2p0TmJEeyUrPCKx7tUYQ" name="project" content="project" type="TYPE_VARIABLE" returnType="com.company.model.Project">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_T8bjoDmJEeyUrPCKx7tUYQ" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_LU2p0jmJEeyUrPCKx7tUYQ" name="applicantEmail" content="applicantEmail" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_LU2p0zmJEeyUrPCKx7tUYQ" type="JAVA_METHOD" expression="setApplicantEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </messageContent>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Zbu6YDmIEeyUrPCKx7tUYQ" name="Notify proposal refusal" outgoing="_kM7MEDmIEeyUrPCKx7tUYQ" incoming="_jh7HQDmIEeyUrPCKx7tUYQ _Zb7usDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZbwvkDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZbwIgDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZbwvkTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_hOwc4DmrEeyLt7tqtTR4OA" name="notifyProposalRefusalByManagement" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_hOwc4TmrEeyLt7tqtTR4OA" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD8DmrEeyLt7tqtTR4OA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD8TmrEeyLt7tqtTR4OA" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD8jmrEeyLt7tqtTR4OA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD8zmrEeyLt7tqtTR4OA" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD9DmrEeyLt7tqtTR4OA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD9TmrEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD9jmrEeyLt7tqtTR4OA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD9zmrEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD-DmrEeyLt7tqtTR4OA" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD-TmrEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD-jmrEeyLt7tqtTR4OA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD-zmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD_DmrEeyLt7tqtTR4OA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD_TmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxD_jmrEeyLt7tqtTR4OA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_hOxD_zmrEeyLt7tqtTR4OA" name="from()" content="&quot;project_status@acme.com&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEAjmrEeyLt7tqtTR4OA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_hOxEAzmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEBDmrEeyLt7tqtTR4OA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_hOxEBTmrEeyLt7tqtTR4OA" name="to()" content="project.applicantEmail&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hOxEBjmrEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEBzmrEeyLt7tqtTR4OA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_hOxECDmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxECTmrEeyLt7tqtTR4OA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_hOxECjmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxECzmrEeyLt7tqtTR4OA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_hOxEDDmrEeyLt7tqtTR4OA" name="subject()" content="&quot;Proposal \&quot;&quot;.concat(project.title.concat(&quot;\&quot; was rejected by management&quot;))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_geww4EDeEeybB7ET8tJHKg" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEDjmrEeyLt7tqtTR4OA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_hOxEDzmrEeyLt7tqtTR4OA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEEDmrEeyLt7tqtTR4OA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_hOxEETmrEeyLt7tqtTR4OA" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEEjmrEeyLt7tqtTR4OA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_hOxEEzmrEeyLt7tqtTR4OA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEFDmrEeyLt7tqtTR4OA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_hOxEFTmrEeyLt7tqtTR4OA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEFjmrEeyLt7tqtTR4OA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_hOxEFzmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hOxEGDmrEeyLt7tqtTR4OA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_hOxEGTmrEeyLt7tqtTR4OA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZbwvkjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZbwvkzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZbwvlDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZbwvljmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZbwvlTmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Y2ll8DmIEeyUrPCKx7tUYQ" name="Notify proposal approved" outgoing="_oZPbgDmIEeyUrPCKx7tUYQ" incoming="_Y2sToDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Y2mNATmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Y2mNADmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Y2mNAjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_bu69oEDeEeybB7ET8tJHKg" name="notifyProposalApprovalByManagement1" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_bu69oUDeEeybB7ET8tJHKg" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu69okDeEeybB7ET8tJHKg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_bu7ksEDeEeybB7ET8tJHKg" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7ksUDeEeybB7ET8tJHKg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kskDeEeybB7ET8tJHKg" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7ks0DeEeybB7ET8tJHKg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_bu7ktEDeEeybB7ET8tJHKg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7ktUDeEeybB7ET8tJHKg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_bu7ktkDeEeybB7ET8tJHKg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kt0DeEeybB7ET8tJHKg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kuEDeEeybB7ET8tJHKg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kuUDeEeybB7ET8tJHKg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kukDeEeybB7ET8tJHKg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7ku0DeEeybB7ET8tJHKg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kvEDeEeybB7ET8tJHKg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kvUDeEeybB7ET8tJHKg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kvkDeEeybB7ET8tJHKg" name="from()" content="&quot;project_status@acme.com&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kv0DeEeybB7ET8tJHKg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kwEDeEeybB7ET8tJHKg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kwUDeEeybB7ET8tJHKg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kwkDeEeybB7ET8tJHKg" name="to()" content="project.applicantEmail&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bu7kw0DeEeybB7ET8tJHKg" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kxEDeEeybB7ET8tJHKg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kxUDeEeybB7ET8tJHKg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kxkDeEeybB7ET8tJHKg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kx0DeEeybB7ET8tJHKg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kyEDeEeybB7ET8tJHKg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kyUDeEeybB7ET8tJHKg" name="subject()" content="&quot;Proposal \&quot;&quot;.concat(project.title.concat(&quot;\&quot; approved by management!&quot;))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bu7kykDeEeybB7ET8tJHKg" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7ky0DeEeybB7ET8tJHKg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kzEDeEeybB7ET8tJHKg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kzUDeEeybB7ET8tJHKg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_bu7kzkDeEeybB7ET8tJHKg" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7kz0DeEeybB7ET8tJHKg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_bu7k0EDeEeybB7ET8tJHKg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7k0UDeEeybB7ET8tJHKg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_bu7k0kDeEeybB7ET8tJHKg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7k00DeEeybB7ET8tJHKg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_bu7k1EDeEeybB7ET8tJHKg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bu7k1UDeEeybB7ET8tJHKg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_bu7k1kDeEeybB7ET8tJHKg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Y2mNAzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Y2mNBDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Y2mNBTmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Y2mNBzmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Y2mNBjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_kMypMDmIEeyUrPCKx7tUYQ" name="Proposal refused" incoming="_kM7MEDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kMz3UTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kMz3UDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kMz3UjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Yn1YQDmIEeyUrPCKx7tUYQ" name="Proposal approved?" outgoing="_Y2sToDmIEeyUrPCKx7tUYQ _Zb7usDmIEeyUrPCKx7tUYQ" incoming="_XnlcMDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XnTvYTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XnTvYDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XnUWcDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_qRVlkDmIEeyUrPCKx7tUYQ" name="Notify delay" outgoing="_y5JI4DmIEeyUrPCKx7tUYQ" incoming="_xS8AEDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qRVlkjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qRVlkTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qRVlkzmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_jl23IDmrEeyLt7tqtTR4OA" name="notifyDelay" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_jl23ITmrEeyLt7tqtTR4OA" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23IjmrEeyLt7tqtTR4OA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_jl23IzmrEeyLt7tqtTR4OA" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23JDmrEeyLt7tqtTR4OA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_jl23JTmrEeyLt7tqtTR4OA" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23JjmrEeyLt7tqtTR4OA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_jl23JzmrEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23KDmrEeyLt7tqtTR4OA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_jl23KTmrEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23KjmrEeyLt7tqtTR4OA" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_jl23KzmrEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23LDmrEeyLt7tqtTR4OA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_jl23LTmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23LjmrEeyLt7tqtTR4OA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_jl23LzmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23MDmrEeyLt7tqtTR4OA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_jl23MTmrEeyLt7tqtTR4OA" name="from()" content="&quot;project_status@acme.com&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23NDmrEeyLt7tqtTR4OA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_jl23NTmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23NjmrEeyLt7tqtTR4OA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_jl23NzmrEeyLt7tqtTR4OA" name="to()" content="project.applicantEmail&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_jl23ODmrEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23OTmrEeyLt7tqtTR4OA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_jl23OjmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23OzmrEeyLt7tqtTR4OA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_jl23PDmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23PTmrEeyLt7tqtTR4OA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_jl23PjmrEeyLt7tqtTR4OA" name="subject()" content="&quot;Validation of proposal \&quot;&quot;.concat(project.title.concat(&quot;\&quot; was delayed&quot;))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ybmjYDmrEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23QDmrEeyLt7tqtTR4OA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_jl23QTmrEeyLt7tqtTR4OA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23QjmrEeyLt7tqtTR4OA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_jl23QzmrEeyLt7tqtTR4OA" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23RDmrEeyLt7tqtTR4OA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_jl23RTmrEeyLt7tqtTR4OA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23RjmrEeyLt7tqtTR4OA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_jl23RzmrEeyLt7tqtTR4OA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23SDmrEeyLt7tqtTR4OA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_jl23STmrEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_jl23SjmrEeyLt7tqtTR4OA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_jl23SzmrEeyLt7tqtTR4OA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qRVllDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qRVllTmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qRVlljmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qRVlmDmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qRVllzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:IntermediateErrorCatchEvent" xmi:id="_YT9mwDmYEeyqY_BK0Fb6wA" name="sendDelayError" outgoing="_qoln8DmIEeyUrPCKx7tUYQ" errorCode="sendDelayError"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_q4tHkDmIEeyUrPCKx7tUYQ" name="Notify manual delay" outgoing="_yaXiMDmIEeyUrPCKx7tUYQ" incoming="_qoln8DmIEeyUrPCKx7tUYQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qohWgTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qohWgDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qohWgjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qohWgzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qohWhDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qohWhTmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qohWhzmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qohWhjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_q4tHmjmIEeyUrPCKx7tUYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_oJDtokDfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_q4tHmTmIEeyUrPCKx7tUYQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_q4tHnDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_yaOYQDmIEeyUrPCKx7tUYQ" name="Notification done" incoming="_yaXiMDmIEeyUrPCKx7tUYQ _y5JI4DmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yaPmYTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yaPmYDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yaPmYjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0X2ikDmIEeyUrPCKx7tUYQ" name="Project approval?" outgoing="_1dGTYDmIEeyUrPCKx7tUYQ _4UuAwDmIEeyUrPCKx7tUYQ" incoming="_0DomEDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0DliwDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0Dk7sTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0DliwTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1dAMwDmIEeyUrPCKx7tUYQ" name="Notify project accepted" outgoing="_2PVooDmIEeyUrPCKx7tUYQ" incoming="_1dGTYDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1dBa4TmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1dBa4DmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1dBa4jmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_IwYFoDmvEeyLt7tqtTR4OA" name="notifyProjectAccepted" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_IwYFoTmvEeyLt7tqtTR4OA" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFojmvEeyLt7tqtTR4OA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFozmvEeyLt7tqtTR4OA" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFpDmvEeyLt7tqtTR4OA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFpTmvEeyLt7tqtTR4OA" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFpjmvEeyLt7tqtTR4OA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFpzmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFqDmvEeyLt7tqtTR4OA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFqTmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFqjmvEeyLt7tqtTR4OA" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFqzmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFrDmvEeyLt7tqtTR4OA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFrTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFrjmvEeyLt7tqtTR4OA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFrzmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFsDmvEeyLt7tqtTR4OA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFsTmvEeyLt7tqtTR4OA" name="from()" content="&quot;project_status@acme.com&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFtDmvEeyLt7tqtTR4OA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFtTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFtjmvEeyLt7tqtTR4OA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFtzmvEeyLt7tqtTR4OA" name="to()" content="project.applicantEmail&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_IwYFuDmvEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFuTmvEeyLt7tqtTR4OA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFujmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFuzmvEeyLt7tqtTR4OA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFvDmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFvTmvEeyLt7tqtTR4OA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFvjmvEeyLt7tqtTR4OA" name="subject()" content="&quot;Project \&quot;&quot;.concat(project.title.concat(&quot;\&quot; was accepted!&quot;))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UIt24DmvEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFwDmvEeyLt7tqtTR4OA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFwTmvEeyLt7tqtTR4OA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFwjmvEeyLt7tqtTR4OA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFwzmvEeyLt7tqtTR4OA" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFxDmvEeyLt7tqtTR4OA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_IwYFxTmvEeyLt7tqtTR4OA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFxjmvEeyLt7tqtTR4OA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFxzmvEeyLt7tqtTR4OA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFyDmvEeyLt7tqtTR4OA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_IwYFyTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IwYFyjmvEeyLt7tqtTR4OA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_IwYFyzmvEeyLt7tqtTR4OA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1dBa4zmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1dBa5DmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1dBa5TmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1dBa5zmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1dBa5jmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_23FlIDmIEeyUrPCKx7tUYQ" name="Notify project delivery" outgoing="_3ZeggDmIEeyUrPCKx7tUYQ" incoming="_23PWIDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_23GzQTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_23GzQDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_23GzQjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_PC_TMDmvEeyLt7tqtTR4OA" name="notifyProjectDelivery" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_PC_TMTmvEeyLt7tqtTR4OA" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TMjmvEeyLt7tqtTR4OA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TMzmvEeyLt7tqtTR4OA" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TNDmvEeyLt7tqtTR4OA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TNTmvEeyLt7tqtTR4OA" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TNjmvEeyLt7tqtTR4OA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TNzmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TODmvEeyLt7tqtTR4OA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TOTmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TOjmvEeyLt7tqtTR4OA" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TOzmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TPDmvEeyLt7tqtTR4OA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TPTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TPjmvEeyLt7tqtTR4OA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TPzmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TQDmvEeyLt7tqtTR4OA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TQTmvEeyLt7tqtTR4OA" name="from()" content="&quot;project_status@acme.com&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TRDmvEeyLt7tqtTR4OA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TRTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TRjmvEeyLt7tqtTR4OA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TRzmvEeyLt7tqtTR4OA" name="to()" content="project.applicantEmail&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PC_TSDmvEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TSTmvEeyLt7tqtTR4OA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TSjmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TSzmvEeyLt7tqtTR4OA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TTDmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TTTmvEeyLt7tqtTR4OA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TTjmvEeyLt7tqtTR4OA" name="subject()" content="&quot;Project \&quot;&quot;.concat(project.title.concat(&quot;\&quot; is finished!!!&quot;))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_e805sDmvEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TUDmvEeyLt7tqtTR4OA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TUTmvEeyLt7tqtTR4OA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TUjmvEeyLt7tqtTR4OA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TUzmvEeyLt7tqtTR4OA" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TVDmvEeyLt7tqtTR4OA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_PC_TVTmvEeyLt7tqtTR4OA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TVjmvEeyLt7tqtTR4OA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TVzmvEeyLt7tqtTR4OA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TWDmvEeyLt7tqtTR4OA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_PC_TWTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_PC_TWjmvEeyLt7tqtTR4OA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_PC_TWzmvEeyLt7tqtTR4OA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_23HaUDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_23HaUTmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_23HaUjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_23HaVDmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_23HaUzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_3ZUvgDmIEeyUrPCKx7tUYQ" name="Project finished" incoming="_3ZeggDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3ZWksTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3ZWksDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3ZWksjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4UpvUDmIEeyUrPCKx7tUYQ" name="Notify project refused" outgoing="_6ZWK8DmIEeyUrPCKx7tUYQ" incoming="_4UuAwDmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4UqWYTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4UqWYDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4UqWYjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_N2HQYDmvEeyLt7tqtTR4OA" name="notifyProjectRejected" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_N2HQYTmvEeyLt7tqtTR4OA" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQYjmvEeyLt7tqtTR4OA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQYzmvEeyLt7tqtTR4OA" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQZDmvEeyLt7tqtTR4OA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQZTmvEeyLt7tqtTR4OA" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQZjmvEeyLt7tqtTR4OA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQZzmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQaDmvEeyLt7tqtTR4OA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQaTmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQajmvEeyLt7tqtTR4OA" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQazmvEeyLt7tqtTR4OA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQbDmvEeyLt7tqtTR4OA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQbTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQbjmvEeyLt7tqtTR4OA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQbzmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQcDmvEeyLt7tqtTR4OA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQcTmvEeyLt7tqtTR4OA" name="from()" content="&quot;project_status@acme.com&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQdDmvEeyLt7tqtTR4OA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQdTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQdjmvEeyLt7tqtTR4OA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQdzmvEeyLt7tqtTR4OA" name="to()" content="project.applicantEmail&#xA;&#xA;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_N2HQeDmvEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQeTmvEeyLt7tqtTR4OA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQejmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQezmvEeyLt7tqtTR4OA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQfDmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQfTmvEeyLt7tqtTR4OA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQfjmvEeyLt7tqtTR4OA" name="subject()" content="&quot;Project \&quot;&quot;.concat(project.title.concat(&quot;\&quot; was rejected :C&quot;))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Y_fYkDmvEeyLt7tqtTR4OA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQgDmvEeyLt7tqtTR4OA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQgTmvEeyLt7tqtTR4OA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQgjmvEeyLt7tqtTR4OA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQgzmvEeyLt7tqtTR4OA" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQhDmvEeyLt7tqtTR4OA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_N2HQhTmvEeyLt7tqtTR4OA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQhjmvEeyLt7tqtTR4OA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQhzmvEeyLt7tqtTR4OA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQiDmvEeyLt7tqtTR4OA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_N2HQiTmvEeyLt7tqtTR4OA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_N2HQijmvEeyLt7tqtTR4OA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_N2HQizmvEeyLt7tqtTR4OA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4UqWYzmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4UqWZDmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4UqWZTmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4UqWZzmIEeyUrPCKx7tUYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4UqWZjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_6ZOPIDmIEeyUrPCKx7tUYQ" name="Project refused" incoming="_6ZWK8DmIEeyUrPCKx7tUYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6ZO2MTmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6ZO2MDmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6ZO2MjmIEeyUrPCKx7tUYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ROZQEDmJEeyUrPCKx7tUYQ" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ROZ3IDmJEeyUrPCKx7tUYQ" name="init_project()" content="new com.company.model.Project()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Project"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_2T2KoDmHEeyYv-1DyfdLZw">
        <targetForm xmi:type="expression:Expression" xmi:id="_oJDto0DfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_2T2KojmHEeyYv-1DyfdLZw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_Hu-A4EDfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XnlcMDmIEeyUrPCKx7tUYQ" target="_Yn1YQDmIEeyUrPCKx7tUYQ" source="_f8i8ADmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XnlcMTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_XnlcMjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Y2sToDmIEeyUrPCKx7tUYQ" name="Yes" target="_Y2ll8DmIEeyUrPCKx7tUYQ" source="_Yn1YQDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Y2sToTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Y2sTojmIEeyUrPCKx7tUYQ" name="newScript()" content="project.proposalOK == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4dIaQDmmEeyqY_BK0Fb6wA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Zb7usDmIEeyUrPCKx7tUYQ" name="No" target="_Zbu6YDmIEeyUrPCKx7tUYQ" source="_Yn1YQDmIEeyUrPCKx7tUYQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Zb7usTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Zb7usjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jh7HQDmIEeyUrPCKx7tUYQ" target="_Zbu6YDmIEeyUrPCKx7tUYQ" source="_gWIgsDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jh7uUDmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jh7uUTmIEeyUrPCKx7tUYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kM7MEDmIEeyUrPCKx7tUYQ" target="_kMypMDmIEeyUrPCKx7tUYQ" source="_Zbu6YDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kM7zIDmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kM7zITmIEeyUrPCKx7tUYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oZPbgDmIEeyUrPCKx7tUYQ" target="_sCqZQDmIEeyUrPCKx7tUYQ" source="_Y2ll8DmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oZPbgTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oZPbgjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pL2kMDmIEeyUrPCKx7tUYQ" target="_szmuADmIEeyUrPCKx7tUYQ" source="_sCqZQDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pL2kMTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_pL2kMjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qoln8DmIEeyUrPCKx7tUYQ" target="_q4tHkDmIEeyUrPCKx7tUYQ" source="_YT9mwDmYEeyqY_BK0Fb6wA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qoln8TmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qoln8jmIEeyUrPCKx7tUYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xS8AEDmIEeyUrPCKx7tUYQ" target="_qRVlkDmIEeyUrPCKx7tUYQ" source="_vWpSgDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xS8nIDmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_xS8nITmIEeyUrPCKx7tUYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yaXiMDmIEeyUrPCKx7tUYQ" target="_yaOYQDmIEeyUrPCKx7tUYQ" source="_q4tHkDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yaXiMTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_yaXiMjmIEeyUrPCKx7tUYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y5JI4DmIEeyUrPCKx7tUYQ" target="_yaOYQDmIEeyUrPCKx7tUYQ" source="_qRVlkDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y5Jv8DmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_y5Jv8TmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0DomEDmIEeyUrPCKx7tUYQ" target="_0X2ikDmIEeyUrPCKx7tUYQ" source="_szmuADmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0DomETmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0DomEjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1dGTYDmIEeyUrPCKx7tUYQ" name="Yes" target="_1dAMwDmIEeyUrPCKx7tUYQ" source="_0X2ikDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1dGTYTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1dGTYjmIEeyUrPCKx7tUYQ" name="newScript()" content="project.projectOK == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_k98TIDmlEeyqY_BK0Fb6wA" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2PVooDmIEeyUrPCKx7tUYQ" target="_gn4cMEDUEeyXTtv0MKkOFw" source="_1dAMwDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2PVooTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_2PVoojmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_23PWIDmIEeyUrPCKx7tUYQ" target="_23FlIDmIEeyUrPCKx7tUYQ" source="_gn4cMEDUEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_23PWITmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_23PWIjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3ZeggDmIEeyUrPCKx7tUYQ" target="_3ZUvgDmIEeyUrPCKx7tUYQ" source="_23FlIDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3ZeggTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3ZeggjmIEeyUrPCKx7tUYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4UuAwDmIEeyUrPCKx7tUYQ" name="No" target="_4UpvUDmIEeyUrPCKx7tUYQ" source="_0X2ikDmIEeyUrPCKx7tUYQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4UuAwTmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4UuAwjmIEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6ZWK8DmIEeyUrPCKx7tUYQ" target="_6ZOPIDmIEeyUrPCKx7tUYQ" source="_4UpvUDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6ZWK8TmIEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6ZWK8jmIEeyUrPCKx7tUYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g-GqMDmJEeyUrPCKx7tUYQ" target="_f8i8ADmIEeyUrPCKx7tUYQ" source="_SbvpcDmIEeyUrPCKx7tUYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g-GqMTmJEeyUrPCKx7tUYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_g-GqMjmJEeyUrPCKx7tUYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_-I6pcDmHEeyYv-1DyfdLZw" name="Management Assistant"/>
      <actors xmi:type="process:Actor" xmi:id="_AXKCoDmIEeyYv-1DyfdLZw" name="Management"/>
      <actors xmi:type="process:Actor" xmi:id="_DDK88DmIEeyYv-1DyfdLZw" name="R&amp;D" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_2T2KpDmHEeyYv-1DyfdLZw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2T0VcDmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_2T0VcTmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2T0VcjmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2T0VczmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_2T0VdDmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2T0VdTmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2T0VdjmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_2T08gDmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2T08gTmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2T08gjmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_2T08gzmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2T08hDmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_2T08hTmHEeyYv-1DyfdLZw">
        <name xmi:type="expression:Expression" xmi:id="_2T08hjmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_2T08hzmHEeyYv-1DyfdLZw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_gl9JkEDUEeyXTtv0MKkOFw" name="Do project">
      <elements xmi:type="process:Lane" xmi:id="_0ls1gEDUEeyXTtv0MKkOFw" name="R&amp;D" actor="_goHswEDUEeyXTtv0MKkOFw">
        <elements xmi:type="process:EndEvent" xmi:id="_kk8HoEDUEeyXTtv0MKkOFw" name="Project finished" incoming="__qEh4EDUEeyXTtv0MKkOFw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kk-j4EDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kk980EDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kk-j4UDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_nd3ckEDUEeyXTtv0MKkOFw" name="Start project" outgoing="_ob7AQEDUEeyXTtv0MKkOFw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nd4qsUDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nd4qsEDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nd4qskDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_y95xQEDUEeyXTtv0MKkOFw" name="Specify project" outgoing="_rYqeMEDUEeyXTtv0MKkOFw" incoming="_ob7AQEDUEeyXTtv0MKkOFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ob2u0UDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ob2u0EDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ob2u0kDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ob2u00DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ob2u1EDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ob2u1UDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ob2u10DUEeyXTtv0MKkOFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ob2u1kDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_y97mcUDUEeyXTtv0MKkOFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_oGzq4EDfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_y97mcEDUEeyXTtv0MKkOFw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_y97mc0DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_zUV7UEDUEeyXTtv0MKkOFw" name="Implement project" outgoing="_ssUecEDUEeyXTtv0MKkOFw" incoming="_rYqeMEDUEeyXTtv0MKkOFw _PyAOwEDVEeyXTtv0MKkOFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rYgtMEDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rYgGIEDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rYgtMUDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rYgtMkDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rYgtM0DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rYgtNEDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rYgtNkDUEeyXTtv0MKkOFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rYgtNUDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zUWiaUDUEeyXTtv0MKkOFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_oGzq4UDfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zUWiaEDUEeyXTtv0MKkOFw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zUWia0DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_z2VOEEDUEeyXTtv0MKkOFw" name="Test project" outgoing="_D63BoEDVEeyXTtv0MKkOFw" incoming="_ssUecEDUEeyXTtv0MKkOFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ssQNAUDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ssQNAEDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ssQNAkDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_rvGy0EDVEeyXTtv0MKkOFw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rvGy0UDVEeyXTtv0MKkOFw" name="testsPassed" content="testsPassed" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_sOp1kEDVEeyXTtv0MKkOFw" name="testsPassed" dataType="_yr-s6DmHEeyYv-1DyfdLZw"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rvGy0kDVEeyXTtv0MKkOFw" name="testsPassed" content="testsPassed" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_tCGrwEDVEeyXTtv0MKkOFw" name="testsPassed" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_tCGrwUDVEeyXTtv0MKkOFw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rvGy00DVEeyXTtv0MKkOFw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ssQNA0DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ssQNBEDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ssQNBUDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ssQNB0DUEeyXTtv0MKkOFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ssQNBkDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_z2V1JkDUEeyXTtv0MKkOFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_duGWMEDVEeyXTtv0MKkOFw" name="testProject" content="157e5eee-cbf4-470b-89de-e1b66cc92736" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_z2V1JUDUEeyXTtv0MKkOFw">
            <inputs xmi:type="process:ContractInput" xmi:id="_by0VQEDVEeyXTtv0MKkOFw" name="testsPassed" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_by0VQUDVEeyXTtv0MKkOFw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_z2V1KEDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__GjlIEDUEeyXTtv0MKkOFw" name="Deploy project" outgoing="__qEh4EDUEeyXTtv0MKkOFw" incoming="_94UQYEDUEeyXTtv0MKkOFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_94JRQUDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_94JRQEDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_94JRQkDUEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_94JRQ0DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_94JRREDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_94JRRUDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_94J4UEDUEeyXTtv0MKkOFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_94JRRkDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__GlaWUDUEeyXTtv0MKkOFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_oGzq4kDfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__GlaWEDUEeyXTtv0MKkOFw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__GlaW0DUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IPKvcEDVEeyXTtv0MKkOFw" name="Tests passed?" outgoing="_94UQYEDUEeyXTtv0MKkOFw _JkEs4EDVEeyXTtv0MKkOFw" incoming="_D63BoEDVEeyXTtv0MKkOFw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D6o_MUDVEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D6o_MEDVEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D6o_MkDVEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_UGKyoEDVEeyXTtv0MKkOFw" name="Fix project" outgoing="_PyAOwEDVEeyXTtv0MKkOFw" incoming="_JkEs4EDVEeyXTtv0MKkOFw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JkBpkkDVEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JkBpkUDVEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JkBpk0DVEeyXTtv0MKkOFw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JkBplEDVEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JkBplUDVEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JkBplkDVEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JkBpmEDVEeyXTtv0MKkOFw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JkBpl0DVEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_UGMAyUDVEeyXTtv0MKkOFw">
            <targetForm xmi:type="expression:Expression" xmi:id="_oGzq40DfEeybB7ET8tJHKg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_UGMAyEDVEeyXTtv0MKkOFw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_UGMAy0DVEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_goKJAEDUEeyXTtv0MKkOFw" name="project" dataType="_yr-s8DmHEeyYv-1DyfdLZw" className="com.company.model.Project">
        <defaultValue xmi:type="expression:Expression" xmi:id="_goKJAUDUEeyXTtv0MKkOFw" name="Project.findByPersistenceId" content="SELECT p&#xA;FROM Project p&#xA;WHERE p.persistenceId= :persistenceId&#xA;" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.Project">
          <referencedElements xmi:type="expression:Expression" xmi:id="_goKJAkDUEeyXTtv0MKkOFw" name="persistenceId" content="persistenceId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_goKJA0DUEeyXTtv0MKkOFw" name="project_persistenceId" content="project_persistenceId" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Long">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_goKJBEDUEeyXTtv0MKkOFw" name="project_persistenceId" type="LONG"/>
            </referencedElements>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_obcCoEDVEeyXTtv0MKkOFw" name="testsPassed" dataType="_yr-s6DmHEeyYv-1DyfdLZw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_obcCoUDVEeyXTtv0MKkOFw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_gnv5UEDUEeyXTtv0MKkOFw" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_gnv5UUDUEeyXTtv0MKkOFw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_gnv5UkDUEeyXTtv0MKkOFw">
        <targetForm xmi:type="expression:Expression" xmi:id="_gnv5U0DUEeyXTtv0MKkOFw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ob7AQEDUEeyXTtv0MKkOFw" target="_y95xQEDUEeyXTtv0MKkOFw" source="_nd3ckEDUEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ob7AQUDUEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ob7AQkDUEeyXTtv0MKkOFw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rYqeMEDUEeyXTtv0MKkOFw" target="_zUV7UEDUEeyXTtv0MKkOFw" source="_y95xQEDUEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rYqeMUDUEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_rYqeMkDUEeyXTtv0MKkOFw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ssUecEDUEeyXTtv0MKkOFw" target="_z2VOEEDUEeyXTtv0MKkOFw" source="_zUV7UEDUEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ssUecUDUEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ssUeckDUEeyXTtv0MKkOFw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_94UQYEDUEeyXTtv0MKkOFw" name="Yes" target="__GjlIEDUEeyXTtv0MKkOFw" source="_IPKvcEDVEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_94UQYUDUEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_94UQYkDUEeyXTtv0MKkOFw" name="testsPassed==true" content="testsPassed==true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__qEh4EDUEeyXTtv0MKkOFw" target="_kk8HoEDUEeyXTtv0MKkOFw" source="__GjlIEDUEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__qFI8EDUEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="__qFI8UDUEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D63BoEDVEeyXTtv0MKkOFw" target="_IPKvcEDVEeyXTtv0MKkOFw" source="_z2VOEEDUEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D63osEDVEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_D63osUDVEeyXTtv0MKkOFw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JkEs4EDVEeyXTtv0MKkOFw" name="No" target="_UGKyoEDVEeyXTtv0MKkOFw" source="_IPKvcEDVEeyXTtv0MKkOFw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JkEs4UDVEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_JkEs4kDVEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PyAOwEDVEeyXTtv0MKkOFw" target="_zUV7UEDUEeyXTtv0MKkOFw" source="_UGKyoEDVEeyXTtv0MKkOFw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PyDSEEDVEeyXTtv0MKkOFw"/>
        <condition xmi:type="expression:Expression" xmi:id="_PyDSEUDVEeyXTtv0MKkOFw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_goHswEDUEeyXTtv0MKkOFw" name="R&amp;D"/>
      <contract xmi:type="process:Contract" xmi:id="_gnv5VEDUEeyXTtv0MKkOFw">
        <inputs xmi:type="process:ContractInput" xmi:id="_goJh8EDUEeyXTtv0MKkOFw" name="project_persistenceId" type="LONG"/>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gnvSQEDUEeyXTtv0MKkOFw">
        <name xmi:type="expression:Expression" xmi:id="_gnvSQUDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_gnvSQkDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gnvSQ0DUEeyXTtv0MKkOFw">
        <name xmi:type="expression:Expression" xmi:id="_gnvSREDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_gnvSRUDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gnvSRkDUEeyXTtv0MKkOFw">
        <name xmi:type="expression:Expression" xmi:id="_gnvSR0DUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_gnvSSEDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gnvSSUDUEeyXTtv0MKkOFw">
        <name xmi:type="expression:Expression" xmi:id="_gnvSSkDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_gnvSS0DUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gnvSTEDUEeyXTtv0MKkOFw">
        <name xmi:type="expression:Expression" xmi:id="_gnvSTUDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_gnvSTkDUEeyXTtv0MKkOFw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_yr-s6DmHEeyYv-1DyfdLZw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_yr-s6TmHEeyYv-1DyfdLZw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_yr-s6jmHEeyYv-1DyfdLZw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_yr-s6zmHEeyYv-1DyfdLZw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_yr-s7DmHEeyYv-1DyfdLZw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_yr-s7TmHEeyYv-1DyfdLZw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_yr-s7jmHEeyYv-1DyfdLZw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_yr-s7zmHEeyYv-1DyfdLZw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_yr-s8DmHEeyYv-1DyfdLZw" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_9uZbMDmIEeyUrPCKx7tUYQ" name="ProposalSent" target="_SbvpcDmIEeyUrPCKx7tUYQ" source="_yr-sZjmHEeyYv-1DyfdLZw"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_yr-s8jmHEeyYv-1DyfdLZw" type="Process" element="_yr9d8DmHEeyYv-1DyfdLZw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_2T51ADmHEeyYv-1DyfdLZw" type="2007" element="_2R1YcDmHEeyYv-1DyfdLZw">
      <children xmi:type="notation:DecorationNode" xmi:id="_2T6cEDmHEeyYv-1DyfdLZw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_2T6cETmHEeyYv-1DyfdLZw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_3F-yMDmHEeyYv-1DyfdLZw" type="3007" element="_3F7u4DmHEeyYv-1DyfdLZw">
          <children xmi:type="notation:DecorationNode" xmi:id="_3F_ZQDmHEeyYv-1DyfdLZw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_3GAAUDmHEeyYv-1DyfdLZw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_sCrnYDmIEeyUrPCKx7tUYQ" type="3005" element="_sCqZQDmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_sCsOcDmIEeyUrPCKx7tUYQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sCrnYTmIEeyUrPCKx7tUYQ" x="499" y="49" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gn5qUEDUEeyXTtv0MKkOFw" type="3063" element="_gn4cMEDUEeyXTtv0MKkOFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gn6RYEDUEeyXTtv0MKkOFw" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gn5qUUDUEeyXTtv0MKkOFw" x="1031" y="71"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_3F-yMTmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_3F-yMjmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_3F-yMzmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_3GAAUTmHEeyYv-1DyfdLZw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3F-yNDmHEeyYv-1DyfdLZw" x="48" y="10" width="1455" height="142"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_3XUZ0DmHEeyYv-1DyfdLZw" type="3007" element="_3XRWgDmHEeyYv-1DyfdLZw">
          <children xmi:type="notation:DecorationNode" xmi:id="_3XVn8DmHEeyYv-1DyfdLZw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_3XVn8TmHEeyYv-1DyfdLZw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_f8mmYDmIEeyUrPCKx7tUYQ" type="3005" element="_f8i8ADmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f8nNcDmIEeyUrPCKx7tUYQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_gWKV4DmIEeyUrPCKx7tUYQ" type="3043" element="_gWIgsDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
                <children xmi:type="notation:DecorationNode" xmi:id="_gWK88DmIEeyUrPCKx7tUYQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_gWK88TmIEeyUrPCKx7tUYQ" x="-25" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gWKV4TmIEeyUrPCKx7tUYQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f8mmYTmIEeyUrPCKx7tUYQ" x="210" y="25" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_szojMDmIEeyUrPCKx7tUYQ" type="3005" element="_szmuADmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_szpKQTmIEeyUrPCKx7tUYQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_vWruwDmIEeyUrPCKx7tUYQ" type="3064" element="_vWpSgDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
                <children xmi:type="notation:DecorationNode" xmi:id="_vWsV0DmIEeyUrPCKx7tUYQ" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_vWsV0TmIEeyUrPCKx7tUYQ" x="-30" y="-2"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vWruwTmIEeyUrPCKx7tUYQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_szpKQDmIEeyUrPCKx7tUYQ" x="639" y="32" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_3XUZ0TmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_3XUZ0jmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_3XUZ0zmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_3XVn8jmHEeyYv-1DyfdLZw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3XUZ1DmHEeyYv-1DyfdLZw" x="48" y="203" width="1398" height="154"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_3pERIDmHEeyYv-1DyfdLZw" type="3007" element="_3pCb8DmHEeyYv-1DyfdLZw">
          <children xmi:type="notation:DecorationNode" xmi:id="_3pE4MDmHEeyYv-1DyfdLZw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_3pE4MTmHEeyYv-1DyfdLZw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Sbz64DmIEeyUrPCKx7tUYQ" type="3012" element="_SbvpcDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sb0h8DmIEeyUrPCKx7tUYQ" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Sb1JADmIEeyUrPCKx7tUYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sbz64TmIEeyUrPCKx7tUYQ" x="80" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZbzL0DmIEeyUrPCKx7tUYQ" type="3027" element="_Zbu6YDmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZbzL0jmIEeyUrPCKx7tUYQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZbzL0TmIEeyUrPCKx7tUYQ" x="322" y="173" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Y2nbIDmIEeyUrPCKx7tUYQ" type="3027" element="_Y2ll8DmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Y2nbIjmIEeyUrPCKx7tUYQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y2nbITmIEeyUrPCKx7tUYQ" x="322" y="35" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kM1FcDmIEeyUrPCKx7tUYQ" type="3003" element="_kMypMDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_kM1sgDmIEeyUrPCKx7tUYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kM1sgTmIEeyUrPCKx7tUYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kM1FcTmIEeyUrPCKx7tUYQ" x="489" y="188"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Yn30gDmIEeyUrPCKx7tUYQ" type="3008" element="_Yn1YQDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_Yn4bkDmIEeyUrPCKx7tUYQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Yn4bkTmIEeyUrPCKx7tUYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Yn30gTmIEeyUrPCKx7tUYQ" x="255" y="54" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qRWMoDmIEeyUrPCKx7tUYQ" type="3027" element="_qRVlkDmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qRWzsDmIEeyUrPCKx7tUYQ" type="5017"/>
              <children xmi:type="notation:Shape" xmi:id="_YUAqEDmYEeyqY_BK0Fb6wA" type="3032" element="_YT9mwDmYEeyqY_BK0Fb6wA" fontName="Ubuntu">
                <children xmi:type="notation:DecorationNode" xmi:id="_YUBRIDmYEeyqY_BK0Fb6wA" type="5062">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_YUBRITmYEeyqY_BK0Fb6wA" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YUAqETmYEeyqY_BK0Fb6wA"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qRWMoTmIEeyUrPCKx7tUYQ" x="624" y="35"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_q4tuoDmIEeyUrPCKx7tUYQ" type="3005" element="_q4tHkDmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_q4tuojmIEeyUrPCKx7tUYQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_q4tuoTmIEeyUrPCKx7tUYQ" x="638" y="188" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yaQ0gDmIEeyUrPCKx7tUYQ" type="3003" element="_yaOYQDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_yaRbkDmIEeyUrPCKx7tUYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yaRbkTmIEeyUrPCKx7tUYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yaQ0gTmIEeyUrPCKx7tUYQ" x="777" y="198"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0X4XwDmIEeyUrPCKx7tUYQ" type="3008" element="_0X2ikDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_0X4-0DmIEeyUrPCKx7tUYQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0X4-0TmIEeyUrPCKx7tUYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0X4XwTmIEeyUrPCKx7tUYQ" x="838" y="13" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1dCB8DmIEeyUrPCKx7tUYQ" type="3027" element="_1dAMwDmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1dCB8jmIEeyUrPCKx7tUYQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1dCB8TmIEeyUrPCKx7tUYQ" x="918" y="12" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_23IocDmIEeyUrPCKx7tUYQ" type="3027" element="_23FlIDmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_23IocjmIEeyUrPCKx7tUYQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_23IocTmIEeyUrPCKx7tUYQ" x="1161" y="33" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3ZXy0DmIEeyUrPCKx7tUYQ" type="3003" element="_3ZUvgDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_3ZXy0jmIEeyUrPCKx7tUYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3ZXy0zmIEeyUrPCKx7tUYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3ZXy0TmIEeyUrPCKx7tUYQ" x="1315" y="45"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4Uq9cDmIEeyUrPCKx7tUYQ" type="3027" element="_4UpvUDmIEeyUrPCKx7tUYQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4Uq9cjmIEeyUrPCKx7tUYQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4Uq9cTmIEeyUrPCKx7tUYQ" x="916" y="114" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6ZQEUDmIEeyUrPCKx7tUYQ" type="3003" element="_6ZOPIDmIEeyUrPCKx7tUYQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_6ZQrYDmIEeyUrPCKx7tUYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6ZQrYTmIEeyUrPCKx7tUYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6ZQEUTmIEeyUrPCKx7tUYQ" x="1066" y="129"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_3pERITmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_3pERIjmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_3pERIzmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_3pE4MjmHEeyYv-1DyfdLZw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3pERJDmHEeyYv-1DyfdLZw" x="48" y="357" width="1398" height="293"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_2T51ATmHEeyYv-1DyfdLZw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_2T51AjmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_2T51AzmHEeyYv-1DyfdLZw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_2T6cEjmHEeyYv-1DyfdLZw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2T51BDmHEeyYv-1DyfdLZw" width="1478" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_yr_TODmHEeyYv-1DyfdLZw" type="2007" element="_yr-sQTmHEeyYv-1DyfdLZw">
      <children xmi:type="notation:DecorationNode" xmi:id="_yr_TOTmHEeyYv-1DyfdLZw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_yr_TOjmHEeyYv-1DyfdLZw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_yr_TOzmHEeyYv-1DyfdLZw" type="3007" element="_yr-sQjmHEeyYv-1DyfdLZw">
          <children xmi:type="notation:DecorationNode" xmi:id="_yr_TPDmHEeyYv-1DyfdLZw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_yr_TPTmHEeyYv-1DyfdLZw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_yr_TPjmHEeyYv-1DyfdLZw" type="3005" element="_yr-sQzmHEeyYv-1DyfdLZw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yr_TPzmHEeyYv-1DyfdLZw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TQDmHEeyYv-1DyfdLZw" x="175" y="104" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yr_TQTmHEeyYv-1DyfdLZw" type="3008" element="_yr-sYjmHEeyYv-1DyfdLZw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_yr_TQjmHEeyYv-1DyfdLZw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_TQzmHEeyYv-1DyfdLZw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TRDmHEeyYv-1DyfdLZw" x="346" y="107" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yr_TRTmHEeyYv-1DyfdLZw" type="3011" element="_yr-sZjmHEeyYv-1DyfdLZw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_yr_TRjmHEeyYv-1DyfdLZw" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_TRzmHEeyYv-1DyfdLZw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TSDmHEeyYv-1DyfdLZw" x="524" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yr_TSTmHEeyYv-1DyfdLZw" type="3027" element="_yr-sgDmHEeyYv-1DyfdLZw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yr_TSjmHEeyYv-1DyfdLZw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TSzmHEeyYv-1DyfdLZw" x="489" y="161" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yr_TTDmHEeyYv-1DyfdLZw" type="3003" element="_yr-ssTmHEeyYv-1DyfdLZw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_yr_TTTmHEeyYv-1DyfdLZw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_TTjmHEeyYv-1DyfdLZw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TTzmHEeyYv-1DyfdLZw" x="672" y="163"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_yr_TUDmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_yr_TUTmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_yr_TUjmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_yr_TUzmHEeyYv-1DyfdLZw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TVDmHEeyYv-1DyfdLZw" x="48" y="10" width="1297" height="271"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_yr_TVTmHEeyYv-1DyfdLZw" type="3007" element="_yr-stTmHEeyYv-1DyfdLZw">
          <children xmi:type="notation:DecorationNode" xmi:id="_yr_TVjmHEeyYv-1DyfdLZw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_yr_TVzmHEeyYv-1DyfdLZw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_yr_TWDmHEeyYv-1DyfdLZw" type="3002" element="_yr-stjmHEeyYv-1DyfdLZw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_yr_TWTmHEeyYv-1DyfdLZw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_TWjmHEeyYv-1DyfdLZw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TWzmHEeyYv-1DyfdLZw" x="80" y="32" width="30" height="30"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_yr_TXDmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_yr_TXTmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_yr_TXjmHEeyYv-1DyfdLZw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_yr_TXzmHEeyYv-1DyfdLZw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TYDmHEeyYv-1DyfdLZw" x="48" y="100" width="1297" height="122"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_yr_TYTmHEeyYv-1DyfdLZw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_yr_TYjmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_yr_TYzmHEeyYv-1DyfdLZw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_yr_TZDmHEeyYv-1DyfdLZw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yr_TZTmHEeyYv-1DyfdLZw" width="1320" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_gn3OEEDUEeyXTtv0MKkOFw" type="2007" element="_gl9JkEDUEeyXTtv0MKkOFw">
      <children xmi:type="notation:DecorationNode" xmi:id="_gn31IEDUEeyXTtv0MKkOFw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_gn31IUDUEeyXTtv0MKkOFw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_0lvRwEDUEeyXTtv0MKkOFw" type="3007" element="_0ls1gEDUEeyXTtv0MKkOFw">
          <children xmi:type="notation:DecorationNode" xmi:id="_0lvRxUDUEeyXTtv0MKkOFw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_0lv40EDUEeyXTtv0MKkOFw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_klAZEEDUEeyXTtv0MKkOFw" type="3003" element="_kk8HoEDUEeyXTtv0MKkOFw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_klBAIEDUEeyXTtv0MKkOFw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_klBAIUDUEeyXTtv0MKkOFw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_klAZEUDUEeyXTtv0MKkOFw" x="802" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nd6f4EDUEeyXTtv0MKkOFw" type="3002" element="_nd3ckEDUEeyXTtv0MKkOFw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_nd7G8EDUEeyXTtv0MKkOFw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_nd7G8UDUEeyXTtv0MKkOFw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nd6f4UDUEeyXTtv0MKkOFw" x="79" y="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y98NgEDUEeyXTtv0MKkOFw" type="3005" element="_y95xQEDUEeyXTtv0MKkOFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_y98NgkDUEeyXTtv0MKkOFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y98NgUDUEeyXTtv0MKkOFw" x="150" y="100" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zUXJcEDUEeyXTtv0MKkOFw" type="3005" element="_zUV7UEDUEeyXTtv0MKkOFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zUXJckDUEeyXTtv0MKkOFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zUXJcUDUEeyXTtv0MKkOFw" x="289" y="102" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z2V1KUDUEeyXTtv0MKkOFw" type="3005" element="_z2VOEEDUEeyXTtv0MKkOFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_z2V1K0DUEeyXTtv0MKkOFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z2V1KkDUEeyXTtv0MKkOFw" x="407" y="102" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__GmBYEDUEeyXTtv0MKkOFw" type="3005" element="__GjlIEDUEeyXTtv0MKkOFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__GmocEDUEeyXTtv0MKkOFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__GmBYUDUEeyXTtv0MKkOFw" x="655" y="102" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IPLWgEDVEeyXTtv0MKkOFw" type="3008" element="_IPKvcEDVEeyXTtv0MKkOFw" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_IPLWgkDVEeyXTtv0MKkOFw" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IPLWg0DVEeyXTtv0MKkOFw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IPLWgUDVEeyXTtv0MKkOFw" x="553" y="103" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UGMn0EDVEeyXTtv0MKkOFw" type="3005" element="_UGKyoEDVEeyXTtv0MKkOFw" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UGMn0kDVEeyXTtv0MKkOFw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UGMn0UDVEeyXTtv0MKkOFw" x="391" y="180" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_0lvRwUDUEeyXTtv0MKkOFw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_0lvRwkDUEeyXTtv0MKkOFw" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_0lvRw0DUEeyXTtv0MKkOFw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_0lv40UDUEeyXTtv0MKkOFw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0lvRxEDUEeyXTtv0MKkOFw" x="145" y="58"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_gn3OEUDUEeyXTtv0MKkOFw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_gn3OEkDUEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_gn3OE0DUEeyXTtv0MKkOFw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_gn31IkDUEeyXTtv0MKkOFw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gn3OFEDUEeyXTtv0MKkOFw" width="1509" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_yr_TZjmHEeyYv-1DyfdLZw"/>
    <edges xmi:type="notation:Connector" xmi:id="_yr_TzTmHEeyYv-1DyfdLZw" type="4001" element="_yr-swzmHEeyYv-1DyfdLZw" source="_yr_TWDmHEeyYv-1DyfdLZw" target="_yr_TPjmHEeyYv-1DyfdLZw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yr_TzjmHEeyYv-1DyfdLZw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_TzzmHEeyYv-1DyfdLZw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yr_T0DmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yr_T0TmHEeyYv-1DyfdLZw" points="[4, -15, -129, 84]$[4, -100, -129, -1]$[83, -100, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yr_T0jmHEeyYv-1DyfdLZw" type="4001" element="_yr-sxjmHEeyYv-1DyfdLZw" source="_yr_TPjmHEeyYv-1DyfdLZw" target="_yr_TQTmHEeyYv-1DyfdLZw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yr_T0zmHEeyYv-1DyfdLZw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_T1DmHEeyYv-1DyfdLZw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yr_T1TmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yr_T1jmHEeyYv-1DyfdLZw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yr_T1zmHEeyYv-1DyfdLZw" type="4001" element="_yr-syTmHEeyYv-1DyfdLZw" source="_yr_TQTmHEeyYv-1DyfdLZw" target="_yr_TRTmHEeyYv-1DyfdLZw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yr_T2DmHEeyYv-1DyfdLZw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_T2TmHEeyYv-1DyfdLZw" x="3" y="-25"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yr_T2jmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yr_T2zmHEeyYv-1DyfdLZw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yr_T3DmHEeyYv-1DyfdLZw" id="(0.16666666666666666,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yr_T3TmHEeyYv-1DyfdLZw" type="4001" element="_yr-szTmHEeyYv-1DyfdLZw" source="_yr_TQTmHEeyYv-1DyfdLZw" target="_yr_TSTmHEeyYv-1DyfdLZw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yr_T3jmHEeyYv-1DyfdLZw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_T3zmHEeyYv-1DyfdLZw" x="-24" y="22"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yr_T4DmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yr_T4TmHEeyYv-1DyfdLZw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yr_T4jmHEeyYv-1DyfdLZw" type="4001" element="_yr-s0DmHEeyYv-1DyfdLZw" source="_yr_TSTmHEeyYv-1DyfdLZw" target="_yr_TTDmHEeyYv-1DyfdLZw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yr_T4zmHEeyYv-1DyfdLZw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yr_T5DmHEeyYv-1DyfdLZw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yr_T5TmHEeyYv-1DyfdLZw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yr_T5jmHEeyYv-1DyfdLZw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XnmDQDmIEeyUrPCKx7tUYQ" type="4001" element="_XnlcMDmIEeyUrPCKx7tUYQ" source="_f8mmYDmIEeyUrPCKx7tUYQ" target="_Yn30gDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XnmqUDmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XnmqUTmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XnmDQTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XnmDQjmIEeyUrPCKx7tUYQ" points="[45, 25, -46, -135]$[45, 142, -46, -18]$[88, 142, -3, -18]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Y2zoYDmIEeyUrPCKx7tUYQ" type="4001" element="_Y2sToDmIEeyUrPCKx7tUYQ" source="_Yn30gDmIEeyUrPCKx7tUYQ" target="_Y2nbIDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Y2zoYzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Y2zoZDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Y2zoYTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Y2zoYjmIEeyUrPCKx7tUYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZcFfsDmIEeyUrPCKx7tUYQ" type="4001" element="_Zb7usDmIEeyUrPCKx7tUYQ" source="_Yn30gDmIEeyUrPCKx7tUYQ" target="_ZbzL0DmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZcGGwDmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZcGGwTmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZcFfsTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZcFfsjmIEeyUrPCKx7tUYQ" points="[6, 16, -170, -41]$[6, 68, -170, 11]$[162, 68, -14, 11]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gk_88DmlEeyqY_BK0Fb6wA" id="(0.2,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jh88cDmIEeyUrPCKx7tUYQ" type="4001" element="_jh7HQDmIEeyUrPCKx7tUYQ" source="_gWKV4DmIEeyUrPCKx7tUYQ" target="_ZbzL0DmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jh9jgDmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jh9jgTmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jh88cTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jh88cjmIEeyUrPCKx7tUYQ" points="[-19, 0, -116, -271]$[-19, 286, -116, 15]$[71, 286, -26, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jiAm0DmIEeyUrPCKx7tUYQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jiAm0TmIEeyUrPCKx7tUYQ" id="(0.22,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kM8aMDmIEeyUrPCKx7tUYQ" type="4001" element="_kM7MEDmIEeyUrPCKx7tUYQ" source="_ZbzL0DmIEeyUrPCKx7tUYQ" target="_kM1FcDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kM8aMzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kM9BQDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kM8aMTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kM8aMjmIEeyUrPCKx7tUYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oZQCkDmIEeyUrPCKx7tUYQ" type="4001" element="_oZPbgDmIEeyUrPCKx7tUYQ" source="_Y2nbIDmIEeyUrPCKx7tUYQ" target="_sCrnYDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oZQCkzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oZQClDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oZQCkTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oZQCkjmIEeyUrPCKx7tUYQ" points="[11, -30, -136, 337]$[11, -373, -136, -6]$[97, -373, -50, -6]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pL3LQDmIEeyUrPCKx7tUYQ" type="4001" element="_pL2kMDmIEeyUrPCKx7tUYQ" source="_sCrnYDmIEeyUrPCKx7tUYQ" target="_szojMDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pL3yUDmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pL3yUTmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pL3LQTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pL3LQjmIEeyUrPCKx7tUYQ" points="[50, -6, -110, -211]$[140, -6, -20, -211]$[140, 180, -20, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qoln8zmIEeyUrPCKx7tUYQ" type="4001" element="_qoln8DmIEeyUrPCKx7tUYQ" source="_YUAqEDmYEeyqY_BK0Fb6wA" target="_q4tuoDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qoln9jmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qoln9zmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qoln9DmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qoln9TmIEeyUrPCKx7tUYQ" points="[7, 13, -29, -111]$[7, 99, -29, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xTA4kDmIEeyUrPCKx7tUYQ" type="4001" element="_xS8AEDmIEeyUrPCKx7tUYQ" source="_vWruwDmIEeyUrPCKx7tUYQ" target="_qRWMoDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xTA4kzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xTA4lDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xTA4kTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xTA4kjmIEeyUrPCKx7tUYQ" points="[-12, 0, -18, -240]$[9, 215, 3, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xTFKADmIEeyUrPCKx7tUYQ" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yaYJQDmIEeyUrPCKx7tUYQ" type="4001" element="_yaXiMDmIEeyUrPCKx7tUYQ" source="_q4tuoDmIEeyUrPCKx7tUYQ" target="_yaQ0gDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yaYJQzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yaYwUDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yaYJQTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yaYJQjmIEeyUrPCKx7tUYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y5K-EDmIEeyUrPCKx7tUYQ" type="4001" element="_y5JI4DmIEeyUrPCKx7tUYQ" source="_qRWMoDmIEeyUrPCKx7tUYQ" target="_yaQ0gDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y5K-EzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y5LlIDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y5K-ETmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y5K-EjmIEeyUrPCKx7tUYQ" points="[0, 0, -52, -56]$[50, 70, -2, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y5OBYDmIEeyUrPCKx7tUYQ" id="(1.0,0.66)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0DomEzmIEeyUrPCKx7tUYQ" type="4001" element="_0DomEDmIEeyUrPCKx7tUYQ" source="_szojMDmIEeyUrPCKx7tUYQ" target="_0X4XwDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0DpNIDmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0DpNITmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0DomFDmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0DomFTmIEeyUrPCKx7tUYQ" points="[50, -1, -120, -132]$[170, -1, 0, -132]$[170, 110, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1dG6cDmIEeyUrPCKx7tUYQ" type="4001" element="_1dGTYDmIEeyUrPCKx7tUYQ" source="_0X4XwDmIEeyUrPCKx7tUYQ" target="_1dCB8DmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1dG6czmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1dG6dDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1dG6cTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1dG6cjmIEeyUrPCKx7tUYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2PWPsDmIEeyUrPCKx7tUYQ" type="4001" element="_2PVooDmIEeyUrPCKx7tUYQ" source="_1dCB8DmIEeyUrPCKx7tUYQ" target="_gn5qUEDUEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2PWPszmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2PWPtDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2PWPsTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2PWPsjmIEeyUrPCKx7tUYQ" points="[14, -30, -65, 314]$[14, -344, -65, 0]$[29, -344, -50, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_23QkQDmIEeyUrPCKx7tUYQ" type="4001" element="_23PWIDmIEeyUrPCKx7tUYQ" source="_gn5qUEDUEeyXTtv0MKkOFw" target="_23IocDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_23QkQzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_23QkRDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_23QkQTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_23QkQjmIEeyUrPCKx7tUYQ" points="[50, 0, -63, -342]$[68, 0, -45, -342]$[68, 312, -45, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3ZfHkDmIEeyUrPCKx7tUYQ" type="4001" element="_3ZeggDmIEeyUrPCKx7tUYQ" source="_23IocDmIEeyUrPCKx7tUYQ" target="_3ZXy0DmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3ZfHkzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3ZfHlDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3ZfHkTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3ZfHkjmIEeyUrPCKx7tUYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4UwdADmIEeyUrPCKx7tUYQ" type="4001" element="_4UuAwDmIEeyUrPCKx7tUYQ" source="_0X4XwDmIEeyUrPCKx7tUYQ" target="_4Uq9cDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4UwdAzmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4UwdBDmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4UwdATmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4UwdAjmIEeyUrPCKx7tUYQ" points="[0, 22, -107, -83]$[0, 104, -107, -1]$[53, 104, -54, -1]$[53, 109, -54, 4]$[57, 109, -50, 4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6ZWyADmIEeyUrPCKx7tUYQ" type="4001" element="_6ZWK8DmIEeyUrPCKx7tUYQ" source="_4Uq9cDmIEeyUrPCKx7tUYQ" target="_6ZQEUDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6ZXZEDmIEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6ZXZETmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6ZWyATmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6ZWyAjmIEeyUrPCKx7tUYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9uaCQDmIEeyUrPCKx7tUYQ" type="4002" element="_9uZbMDmIEeyUrPCKx7tUYQ" source="_yr_TRTmHEeyYv-1DyfdLZw" target="_Sbz64DmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9uapUDmIEeyUrPCKx7tUYQ" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9uapUTmIEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9uaCQTmIEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9uaCQjmIEeyUrPCKx7tUYQ" points="[-14, -8, 430, 228]$[-231, -8, 213, 228]$[-231, -15, 213, 221]$[-444, -15, 0, 221]$[-444, -222, 0, 14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g-HRQDmJEeyUrPCKx7tUYQ" type="4001" element="_g-GqMDmJEeyUrPCKx7tUYQ" source="_Sbz64DmIEeyUrPCKx7tUYQ" target="_f8mmYDmIEeyUrPCKx7tUYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g-H4UDmJEeyUrPCKx7tUYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g-H4UTmJEeyUrPCKx7tUYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g-HRQTmJEeyUrPCKx7tUYQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g-HRQjmJEeyUrPCKx7tUYQ" points="[7, -14, -112, 187]$[7, -214, -112, -13]$[115, -214, -4, -13]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e7qnoDmlEeyqY_BK0Fb6wA" id="(0.04,0.86)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ob7AQ0DUEeyXTtv0MKkOFw" type="4001" element="_ob7AQEDUEeyXTtv0MKkOFw" source="_nd6f4EDUEeyXTtv0MKkOFw" target="_y98NgEDUEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ob7nUEDUEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ob7nUUDUEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ob7AREDUEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ob7ARUDUEeyXTtv0MKkOFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rYrFQEDUEeyXTtv0MKkOFw" type="4001" element="_rYqeMEDUEeyXTtv0MKkOFw" source="_y98NgEDUEeyXTtv0MKkOFw" target="_zUXJcEDUEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rYrsUkDUEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rYrsU0DUEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rYrsUEDUEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rYrsUUDUEeyXTtv0MKkOFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ssVFgEDUEeyXTtv0MKkOFw" type="4001" element="_ssUecEDUEeyXTtv0MKkOFw" source="_zUXJcEDUEeyXTtv0MKkOFw" target="_z2V1KUDUEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ssVskEDUEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ssVskUDUEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ssVFgUDUEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ssVFgkDUEeyXTtv0MKkOFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_94VegEDUEeyXTtv0MKkOFw" type="4001" element="_94UQYEDUEeyXTtv0MKkOFw" source="_IPLWgEDVEeyXTtv0MKkOFw" target="__GmBYEDUEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_94Veg0DUEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_94VehEDUEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_94VegUDUEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_94VegkDUEeyXTtv0MKkOFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__qFwAEDUEeyXTtv0MKkOFw" type="4001" element="__qEh4EDUEeyXTtv0MKkOFw" source="__GmBYEDUEeyXTtv0MKkOFw" target="_klAZEEDUEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__qGXEEDUEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__qGXEUDUEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__qFwAUDUEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__qFwAkDUEeyXTtv0MKkOFw" points="[0, -2, -59, 0]$[44, -2, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__qIzUEDUEeyXTtv0MKkOFw" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D64PwEDVEeyXTtv0MKkOFw" type="4001" element="_D63BoEDVEeyXTtv0MKkOFw" source="_z2V1KUDUEeyXTtv0MKkOFw" target="_IPLWgEDVEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_D64Pw0DVEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D64PxEDVEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D64PwUDVEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D64PwkDVEeyXTtv0MKkOFw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JkHwMEDVEeyXTtv0MKkOFw" type="4001" element="_JkEs4EDVEeyXTtv0MKkOFw" source="_IPLWgEDVEeyXTtv0MKkOFw" target="_UGMn0EDVEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JkHwM0DVEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JkIXQEDVEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JkHwMUDVEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JkHwMkDVEeyXTtv0MKkOFw" points="[0, 22, 133, -59]$[0, 78, 133, -3]$[-83, 78, 50, -3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PyEgMEDVEeyXTtv0MKkOFw" type="4001" element="_PyAOwEDVEeyXTtv0MKkOFw" source="_UGMn0EDVEeyXTtv0MKkOFw" target="_zUXJcEDUEeyXTtv0MKkOFw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PyEgM0DVEeyXTtv0MKkOFw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PyEgNEDVEeyXTtv0MKkOFw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PyEgMUDVEeyXTtv0MKkOFw" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PyEgMkDVEeyXTtv0MKkOFw" points="[-100, -5, 40, 64]$[-145, -5, -5, 64]$[-145, -58, -5, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PyHjgEDVEeyXTtv0MKkOFw" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PyHjgUDVEeyXTtv0MKkOFw" id="(0.62,0.78)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
